### ISSUE TITLE
catch sequelize uniqueness errors

### ISSUE THREAD

**Issue by Noslepr** [ntseng/w12-groupproject#66]
```
		console.log(validatorErrors.array().map(error => error.msg));//TODO 
```

undefined

**Comment by Noslepr** [comment]
[git push --set-upstream origin Noslepr/issue15](https://stackoverflow.com/questions/65708882/how-to-check-if-a-field-is-unique-in-express-validator)

**Comment by ntseng** [comment]
https://stackoverflow.com/questions/65708882/how-to-check-if-a-field-is-unique-in-express-validator
